CREATE TABLE IF NOT EXISTS public.flow_workflow_versions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid character varying(36) NOT NULL UNIQUE,
    "workflowUuid" character varying(36) NOT NULL,
    "versionNumber" integer NOT NULL,
    name character varying(255),
    definition jsonb NOT NULL,
    "createdBy" character varying(36),
    "createdAt" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS flow_workflow_versions_workflow_version_unq
    ON public.flow_workflow_versions ("workflowUuid", "versionNumber");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'flow_workflow_versions_workflowUuid_fkey'
          AND conrelid = 'public.flow_workflow_versions'::regclass
    ) THEN
        ALTER TABLE public.flow_workflow_versions
            ADD CONSTRAINT "flow_workflow_versions_workflowUuid_fkey"
            FOREIGN KEY ("workflowUuid")
            REFERENCES public.flow_workflows(uuid)
            ON UPDATE CASCADE;
    END IF;
END
$$;
