CREATE TABLE IF NOT EXISTS public.api_idempotency_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid character varying(36) NOT NULL UNIQUE,
    "userUuid" character varying(36) NOT NULL,
    "apiKeyUuid" character varying(36) NOT NULL,
    "key" character varying(255) NOT NULL,
    method character varying(10) NOT NULL,
    path character varying(1024) NOT NULL,
    fingerprint character varying(64) NOT NULL,
    state character varying(16) NOT NULL DEFAULT 'processing',
    "statusCode" integer,
    "responseBody" json,
    "expiresAt" timestamp with time zone NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS api_idempotency_keys_request_unq
    ON public.api_idempotency_keys ("userUuid", "apiKeyUuid", method, path, "key");

CREATE INDEX IF NOT EXISTS api_idempotency_keys_expires_at
    ON public.api_idempotency_keys ("expiresAt");
